#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
version: "3.8"

services:
  orthanc:
    build:
      context: .
      dockerfile: ./orthanc/Dockerfile
    command: /run/secrets
    env_file:
      - local.env
    environment:
      ORTHANC_NAME: "AzureDICOMProxy"
      ORTHANC_USERNAME: ${ORTHANC_USERNAME}
      ORTHANC_PASSWORD: ${ORTHANC_PASSWORD}
      ORTHANC_AE_TITLE: ${ORTHANC_AE_TITLE}
      ORTHANC_AUTOROUTE_TO_AZURE: ${ORTHANC_AUTOROUTE_TO_AZURE}
      SOURCE_AE_TITLE: ${SOURCE_AE_TITLE}
      SOURCE_DICOM_PORT: ${SOURCE_DICOM_PORT}
      SOURCE_HOSTNAME: ${SOURCE_HOSTNAME}
      DICOM_WEB_PLUGIN_ENABLED: ${ENABLE_DICOM_WEB}
      HTTP_TIMEOUT: ${ORTHANC_HTTP_TIMEOUT}
      AZ_DICOM_ENDPOINT_NAME: ${AZ_DICOM_ENDPOINT_NAME}
      AZ_DICOM_ENDPOINT_URL: ${AZ_DICOM_ENDPOINT_URL}
      AZ_DICOM_ENDPOINT_CLIENT_ID: ${AZ_DICOM_ENDPOINT_CLIENT_ID}
      AZ_DICOM_ENDPOINT_CLIENT_SECRET: ${AZ_DICOM_ENDPOINT_CLIENT_SECRET}
      AZ_DICOM_ENDPOINT_TENANT_ID: ${AZ_DICOM_ENDPOINT_TENANT_ID}
      AZ_DICOM_TOKEN_REFRESH_SECS: "600"
      ENV: ${ENV}
      DEBUG: ${DEBUG}
    ports:
      - "${ORTHANC_DICOM_PORT}:4242"
      - "${ORTHANC_WEB_PORT}:8042"
    volumes:
      - ./orthanc-data:/var/lib/orthanc/db
      - ./orthanc/config:/run/secrets:ro
    networks:
      - pixl-net
    # depends_on:
      # postgres:
      #   condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "-u" , "${ORTHANC_USERNAME}:${ORTHANC_PASSWORD}", "http://orthanc:8042/heart-beat" ]
      interval: 10s
      timeout: 30s
      retries: 5
    restart: "no"

networks:
  pixl-net:

